[[language]]
name = "go"
auto-format = false

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "vue"
formatter = { command = "prettier", args = ["--parser", "vue"] }
auto-format = false
language-servers = ["vtsls", "vue-language-server"]

[[language]]
name = "zig"
auto-format = false

# Language servers.

[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.vtsls.config]
hostInfo = "helix"
vtsls.tsserver.globalPlugins = [
  { name = "@vue/typescript-plugin", location = "~/.bun/install/global/node_modules/@vue/language-server", languages = [
    "vue",
  ], configNamespace = "typescript" },
]
